#!/usr/bin/env python3
"""Generate current AscNet login config from a decoded retail NotifyLogin dump.

This intentionally overwrites the single current server config. It does not create
versioned season bundles; Steam/launcher clients cannot stay on old versions.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "AscNet.GameServer" / "Handlers" / "AccountModule.TimeLimitControls.cs"


def require_list(root: dict[str, Any], key: str, source: Path) -> list[Any]:
    value = root.get(key)
    if not isinstance(value, list):
        raise ValueError(f"{source}: expected {key} to be a list, got {type(value).__name__}.")
    return value


def require_int(record: Any, key: str, source: Path, index: int, list_name: str) -> int:
    if not isinstance(record, dict):
        raise ValueError(f"{source}: {list_name}[{index}] must be an object, got {type(record).__name__}.")
    value = record.get(key)
    if not isinstance(value, int):
        raise ValueError(f"{source}: {list_name}[{index}].{key} must be an integer, got {value!r}.")
    return value


def load_notify_login(path: Path) -> tuple[list[tuple[int, int, int]], list[tuple[int, int]]]:
    with path.open("r", encoding="utf-8") as handle:
        root = json.load(handle)
    if not isinstance(root, dict):
        raise ValueError(f"{path}: expected NotifyLogin root object, got {type(root).__name__}.")

    time_limit_rows: list[tuple[int, int, int]] = []
    seen_time_ids: set[int] = set()
    for index, record in enumerate(require_list(root, "TimeLimitCtrlConfigList", path)):
        control_id = require_int(record, "Id", path, index, "TimeLimitCtrlConfigList")
        start_time = require_int(record, "StartTime", path, index, "TimeLimitCtrlConfigList")
        end_time = require_int(record, "EndTime", path, index, "TimeLimitCtrlConfigList")
        if control_id in seen_time_ids:
            raise ValueError(f"{path}: duplicate TimeLimitCtrlConfigList Id {control_id}.")
        seen_time_ids.add(control_id)
        time_limit_rows.append((control_id, start_time, end_time))

    function_rows: list[tuple[int, int]] = []
    seen_functions: set[tuple[int, int]] = set()
    for index, record in enumerate(require_list(root, "FunctionOpenTimeConfigList", path)):
        function_id = require_int(record, "FunctionId", path, index, "FunctionOpenTimeConfigList")
        time_id = require_int(record, "TimeId", path, index, "FunctionOpenTimeConfigList")
        key = (function_id, time_id)
        if key in seen_functions:
            raise ValueError(f"{path}: duplicate FunctionOpenTimeConfigList pair FunctionId={function_id}, TimeId={time_id}.")
        seen_functions.add(key)
        function_rows.append(key)

    if not time_limit_rows:
        raise ValueError(f"{path}: TimeLimitCtrlConfigList is empty; refusing to generate a broken login config.")

    return time_limit_rows, function_rows


def generate_source(source_path: Path, time_limit_rows: list[tuple[int, int, int]], function_rows: list[tuple[int, int]]) -> str:
    source_label = source_path.name
    lines: list[str] = [
        "// <auto-generated>",
        f"// Generated by Scripts/generate_current_login_config.py from {source_label}.",
        "// Do not edit by hand; regenerate from the latest retail NotifyLogin dump.",
        "// </auto-generated>",
        "using AscNet.Common.MsgPack;",
        "",
        "namespace AscNet.GameServer.Handlers",
        "{",
        "    internal partial class AccountModule",
        "    {",
        "        private static readonly (long Id, long StartTime, long EndTime)[] CurrentDrawTimeLimitControls =",
        "        [",
    ]

    for index, (control_id, start_time, end_time) in enumerate(time_limit_rows):
        comma = "," if index < len(time_limit_rows) - 1 else ""
        lines.append(f"            ({control_id}, {start_time}, {end_time}){comma}")

    lines.extend(
        [
            "        ];",
            "",
            "        private static List<FunctionOpenTimeConfig> BuildFunctionOpenTimeConfigList()",
            "        {",
        ]
    )

    if function_rows:
        lines.extend(["            return", "            ["])
        for index, (function_id, time_id) in enumerate(function_rows):
            comma = "," if index < len(function_rows) - 1 else ""
            lines.extend(
                [
                    "                new()",
                    "                {",
                    f"                    FunctionId = {function_id},",
                    f"                    TimeId = {time_id}",
                    f"                }}{comma}",
                ]
            )
        lines.append("            ];")
    else:
        lines.append("            return [];")

    lines.extend(
        [
            "        }",
            "    }",
            "}",
        ]
    )
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the current server login time/function gates from a decoded retail NotifyLogin JSON dump. "
            "This updates the single latest config, not versioned season bundles."
        )
    )
    parser.add_argument(
        "--notify-login",
        required=True,
        type=Path,
        help="Path to decoded retail NotifyLogin.json, e.g. .runtime/20260706_1451.dumps/0639-NotifyLogin.json.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Generated C# output path. Default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT).as_posix()}.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero if the output file is missing or stale.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    notify_login = args.notify_login
    output = args.output

    time_limit_rows, function_rows = load_notify_login(notify_login)
    generated = generate_source(notify_login, time_limit_rows, function_rows)

    if args.check:
        if not output.exists():
            print(f"stale: {output} does not exist", file=sys.stderr)
            return 1
        existing = output.read_text(encoding="utf-8")
        if existing != generated:
            print(f"stale: {output} differs from {notify_login}", file=sys.stderr)
            print(f"time_limit_controls={len(time_limit_rows)} function_open_times={len(function_rows)}", file=sys.stderr)
            return 1
        print(f"up-to-date: {output}")
        print(f"time_limit_controls={len(time_limit_rows)} function_open_times={len(function_rows)}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")
    print(f"generated: {output}")
    print(f"time_limit_controls={len(time_limit_rows)} function_open_times={len(function_rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
